// app.js

const LINEUP = {
  Thursday: {
    date: "Thu 6 Aug 2026",
    bands: [
      // Empress Ballroom
      { name: "THE STRANGLERS", stage: "Empress Ballroom", start: "22:45", end: "00:15" },
      { name: "SLAUGHTER & THE DOGS", stage: "Empress Ballroom", start: "21:15", end: "22:15" },
      { name: "STEVE IGNORANT BAND CRASS SET", stage: "Empress Ballroom", start: "19:45", end: "20:45" },
      { name: "UK SUBS", stage: "Empress Ballroom", start: "18:20", end: "19:20" },
      { name: "BAR STOOL PREACHERS", stage: "Empress Ballroom", start: "17:10", end: "17:55" },
      { name: "THE COURETTES", stage: "Empress Ballroom", start: "16:10", end: "16:50" },
      { name: "THE GOOD THE BAD AND THE ZUGLY", stage: "Empress Ballroom", start: "15:10", end: "15:50" },
      { name: "THE DOLLHEADS", stage: "Empress Ballroom", start: "14:15", end: "14:50" },
      { name: "FACE UP", stage: "Empress Ballroom", start: "13:20", end: "13:55" },
      { name: "18 FEVERS", stage: "Empress Ballroom", start: "12:30", end: "13:00" },
      // Club Casbah
      { name: "MILLIE MANDERS & THE SHUT UP", stage: "Club Casbah", start: "23:45", end: "00:45" },
      { name: "MAID OF ACE", stage: "Club Casbah", start: "22:25", end: "23:15" },
      { name: "SCREAM", stage: "Club Casbah", start: "21:10", end: "22:00" },
      { name: "THE ADOLESCENTS", stage: "Club Casbah", start: "19:55", end: "20:45" },
      { name: "THE DROWNS", stage: "Club Casbah", start: "18:50", end: "19:35" },
      { name: "BAD COP BAD COP", stage: "Club Casbah", start: "17:45", end: "18:30" },
      { name: "CONTROL", stage: "Club Casbah", start: "16:45", end: "17:25" },
      { name: "POPES OF CHILLITOWN", stage: "Club Casbah", start: "15:45", end: "16:25" },
      { name: "SLACKRR", stage: "Club Casbah", start: "14:50", end: "15:25" },
      { name: "SUBALTERNOS", stage: "Club Casbah", start: "13:55", end: "14:30" },
      { name: "DOG ROTTEN", stage: "Club Casbah", start: "13:05", end: "13:35" },
      { name: "THE LIARBILITYS", stage: "Club Casbah", start: "12:15", end: "12:45" },
      // Opera House
      { name: "BUZZCOCKS", stage: "Opera House", start: "23:25", end: "00:25" },
      { name: "BOW WOW WOW", stage: "Opera House", start: "22:15", end: "23:05" },
      { name: "AU PAIRS", stage: "Opera House", start: "21:05", end: "21:55" },
      { name: "THE VAPORS", stage: "Opera House", start: "19:55", end: "20:45" },
      { name: "ZION TRAIN", stage: "Opera House", start: "18:50", end: "19:35" },
      { name: "LIGHT OF ETERNITY", stage: "Opera House", start: "17:50", end: "18:30" },
      { name: "BLACK WATER COUNTY", stage: "Opera House", start: "16:45", end: "17:20" },
      { name: "MOLLY VULPYNE BAND", stage: "Opera House", start: "15:55", end: "16:25" },
      { name: "BLYTH POWER", stage: "Opera House", start: "14:55", end: "15:35" },
      { name: "CAROL HODGE BAND", stage: "Opera House", start: "13:55", end: "14:35" },
      { name: "MENACE", stage: "Opera House", start: "12:55", end: "13:35" },
      { name: "HAGAR THE WOMB", stage: "Opera House", start: "12:00", end: "12:35" },
      // Conference Circle
      { name: "THE MOB", stage: "Conference Circle", start: "22:40", end: "23:40" },
      { name: "TV SMITH", stage: "Conference Circle", start: "21:30", end: "22:15" },
      { name: "THE COUNTESS OF FIFE", stage: "Conference Circle", start: "20:30", end: "21:10" },
      // Arena
      { name: "SICK ON THE BUS", stage: "Arena", start: "23:50", end: "00:50" },
      { name: "RIOT CITY RADIO", stage: "Arena", start: "22:50", end: "23:30" },
      { name: "THE BOLOKOS", stage: "Arena", start: "21:50", end: "22:30" },
      { name: "BITE BACK", stage: "Arena", start: "20:50", end: "21:30" },
      { name: "KOMBI KILLERS", stage: "Arena", start: "20:00", end: "20:30" },
      { name: "JANUS STARK", stage: "Arena", start: "19:00", end: "19:40" },
      { name: "HEADSTONE HORRORS", stage: "Arena", start: "18:05", end: "18:40" },
      { name: "FOREIGN LEGION", stage: "Arena", start: "17:10", end: "17:45" },
      { name: "AMBITION DEMOLITION", stage: "Arena", start: "16:20", end: "16:50" },
      { name: "SPLODGENESSABOUNDS", stage: "Arena", start: "15:15", end: "16:00" },
      { name: "DEAD DATES", stage: "Arena", start: "14:25", end: "14:55" },
      { name: "NOOSE", stage: "Arena", start: "13:35", end: "14:05" },
      { name: "LITTERBUG", stage: "Arena", start: "12:45", end: "13:15" },
      // After Dark in Pavilion
      { name: "DRONGOS FOR EUROPE", stage: "After Dark", start: "23:45", end: "00:30" },
      { name: "VOMIT", stage: "After Dark", start: "22:50", end: "23:25" },
      { name: "SKEPTIX", stage: "After Dark", start: "21:55", end: "22:30" },
      { name: "PIZZATRAMP", stage: "After Dark", start: "21:00", end: "21:35" },
      // RIS in Pavilion
      { name: "EX-", stage: "RIS", start: "20:05", end: "20:35" },
      { name: "RED MOON HEROES", stage: "RIS", start: "19:15", end: "19:45" },
      { name: "GRAIL GUARD", stage: "RIS", start: "18:25", end: "18:55" },
      { name: "BE N!CE", stage: "RIS", start: "17:35", end: "18:05" },
      { name: "HAIRDYE", stage: "RIS", start: "16:45", end: "17:15" },
      { name: "THE DOLLIES", stage: "RIS", start: "15:55", end: "16:25" },
      { name: "THE GLITTERBOMBS", stage: "RIS", start: "15:05", end: "15:35" },
      { name: "MINIMAL FAFF", stage: "RIS", start: "14:15", end: "14:45" },
      { name: "AFTRSHOCKS", stage: "RIS", start: "13:25", end: "13:55" },
      { name: "SMOKING FINGERS", stage: "RIS", start: "12:35", end: "13:05" },
      { name: "THROWN AWAY", stage: "RIS", start: "11:45", end: "12:15" },
      // Almost Acoustic
      { name: "BEANS ON TOAST", stage: "Almost Acoustic", start: "20:55", end: "21:45" },
      { name: "MUDDY SUMMERS & THE DFWs", stage: "Almost Acoustic", start: "20:10", end: "20:45" },
      { name: "POPES OF CHILLITOWN (ACOUSTIC)", stage: "Almost Acoustic", start: "19:25", end: "20:00" },
      { name: "SUBALTERNOS (ACOUSTIC)", stage: "Almost Acoustic", start: "18:40", end: "19:15" },
      { name: "BLYTH POWER (ACOUSTIC)", stage: "Almost Acoustic", start: "17:55", end: "18:30" },
      { name: "BABAR LUCK", stage: "Almost Acoustic", start: "17:10", end: "17:45" },
      { name: "ATTILA THE STOCKBROKER POETRY", stage: "Almost Acoustic", start: "16:25", end: "17:00" },
      { name: "JESS SILK", stage: "Almost Acoustic", start: "15:40", end: "16:15" },
      { name: "HENSHAW", stage: "Almost Acoustic", start: "15:00", end: "15:30" },
      { name: "KENT NIELSEN", stage: "Almost Acoustic", start: "14:20", end: "14:50" },
      { name: "IN EVIL HOUR", stage: "Almost Acoustic", start: "13:40", end: "14:10" },
      { name: "DAVID DELINQUENT", stage: "Almost Acoustic", start: "13:00", end: "13:30" },
      // The Old Vic
      { name: "DJS SCARLET AND AYAKO", stage: "The Old Vic", start: "17:00", end: "19:00" },
      { name: "STATIC KILL ACOUSTIC SESSIONS (THU)", stage: "The Old Vic", start: "15:00", end: "17:00" },
      { name: "RAMONA'S TEA PARTY ACOUSTIC", stage: "The Old Vic", start: "14:15", end: "14:45" },
      { name: "NELL DAVIES", stage: "The Old Vic", start: "13:35", end: "14:05" },
      { name: "BATTERY ACID ACOUSTIC", stage: "The Old Vic", start: "12:55", end: "13:25" },
      { name: "RAT BOY'S MAGIC SHOW (THU)", stage: "The Old Vic", start: "12:25", end: "12:45" },
      { name: "BINGO WITH MAX SPLODGE (THU)", stage: "The Old Vic", start: "11:45", end: "12:15" }
    ]
  },

  Friday: {
    date: "Fri 7 Aug 2026",
    bands: [
      // Empress Ballroom
      { name: "SHAM 69", stage: "Empress Ballroom", start: "23:00", end: "00:00" },
      { name: "ANTI NOWHERE LEAGUE", stage: "Empress Ballroom", start: "21:30", end: "22:30" },
      { name: "FEROCIOUS DOG", stage: "Empress Ballroom", start: "20:00", end: "21:00" },
      { name: "GOLDBLADE", stage: "Empress Ballroom", start: "18:50", end: "19:40" },
      { name: "TV SMITH & THE BORED TEENAGERS", stage: "Empress Ballroom", start: "17:30", end: "18:30" },
      { name: "RISKEE AND THE RIDICULE", stage: "Empress Ballroom", start: "16:25", end: "17:10" },
      { name: "LOWER CLASS BRATS", stage: "Empress Ballroom", start: "15:25", end: "16:05" },
      { name: "SPLIT DOGS", stage: "Empress Ballroom", start: "14:30", end: "15:05" },
      { name: "RUMKICKS", stage: "Empress Ballroom", start: "13:35", end: "14:10" },
      { name: "THE WHOPS", stage: "Empress Ballroom", start: "12:45", end: "13:15" },
      // Club Casbah
      { name: "THE BUSINESS", stage: "Club Casbah", start: "00:10", end: "01:00" },
      { name: "THE BOYS", stage: "Club Casbah", start: "22:55", end: "23:45" },
      { name: "BOOZE & GLORY", stage: "Club Casbah", start: "21:45", end: "22:35" },
      { name: "THE QUEERS", stage: "Club Casbah", start: "20:35", end: "21:25" },
      { name: "RANDOM HAND", stage: "Club Casbah", start: "19:30", end: "20:15" },
      { name: "THE KIDS", stage: "Club Casbah", start: "18:20", end: "19:10" },
      { name: "MERYL STREEK", stage: "Club Casbah", start: "17:20", end: "18:00" },
      { name: "CITIZEN FISH", stage: "Club Casbah", start: "16:15", end: "17:00" },
      { name: "UNRIVALLED", stage: "Club Casbah", start: "15:25", end: "15:55" },
      { name: "BROKEN 3 WAYS", stage: "Club Casbah", start: "14:35", end: "15:05" },
      { name: "FANTAZMAZ", stage: "Club Casbah", start: "13:45", end: "14:15" },
      { name: "BATTERY ACID", stage: "Club Casbah", start: "12:55", end: "13:25" },
      // Opera House
      { name: "REZILLOS", stage: "Opera House", start: "23:30", end: "00:30" },
      { name: "LENE LOVICH", stage: "Opera House", start: "22:10", end: "23:00" },
      { name: "BAR STOOL PREACHERS ACOUSTIC", stage: "Opera House", start: "21:05", end: "21:50" },
      { name: "MICK ROSSI'S GUN ST", stage: "Opera House", start: "20:00", end: "20:45" },
      { name: "ROMAN JUGG BAND", stage: "Opera House", start: "18:55", end: "19:40" },
      { name: "JOHN OTWAY & WILD WILLY BARRETT", stage: "Opera House", start: "17:50", end: "18:35" },
      { name: "RADICAL ARCHITECTS", stage: "Opera House", start: "16:50", end: "17:30" },
      { name: "GYPSY PISTOLEROS", stage: "Opera House", start: "15:50", end: "16:30" },
      { name: "LOST CHERREES", stage: "Opera House", start: "14:50", end: "15:30" },
      { name: "50 FOOT WOMAN", stage: "Opera House", start: "13:55", end: "14:30" },
      { name: "MARC VALENTINE", stage: "Opera House", start: "13:00", end: "13:35" },
      // Conference Circle
      { name: "SPEAR OF DESTINY", stage: "Conference Circle", start: "23:00", end: "00:00" },
      { name: "EATER", stage: "Conference Circle", start: "21:40", end: "22:30" },
      // Arena
      { name: "BITE ME BAMBI", stage: "Arena", start: "00:10", end: "01:00" },
      { name: "CULT MANIAX", stage: "Arena", start: "23:00", end: "23:45" },
      { name: "SPECIAL DUTIES", stage: "Arena", start: "21:50", end: "22:40" },
      { name: "THE SAMPLES", stage: "Arena", start: "20:50", end: "21:30" },
      { name: "GATECRASH", stage: "Arena", start: "19:50", end: "20:30" },
      { name: "MDM", stage: "Arena", start: "18:50", end: "19:30" },
      { name: "SPECTRUM 4", stage: "Arena", start: "17:55", end: "18:30" },
      { name: "BULLITZ 23", stage: "Arena", start: "17:00", end: "17:35" },
      { name: "RIVALRY", stage: "Arena", start: "16:05", end: "16:40" },
      { name: "ANTI VIRUS", stage: "Arena", start: "15:15", end: "15:45" },
      { name: "CLUB BRAT", stage: "Arena", start: "14:25", end: "14:55" },
      { name: "COVID 21", stage: "Arena", start: "13:35", end: "14:05" },
      { name: "SPLEEN", stage: "Arena", start: "12:45", end: "13:15" },
      // After Dark in Pavilion
      { name: "SCREAMING DEAD", stage: "After Dark", start: "00:20", end: "01:00" },
      { name: "DEAF DEVILS", stage: "After Dark", start: "23:25", end: "00:00" },
      { name: "BORROWED TIME", stage: "After Dark", start: "22:30", end: "23:05" },
      { name: "THE PUNCTURISTS", stage: "After Dark", start: "21:40", end: "22:10" },
      // RIS in Pavilion
      { name: "TOMORROW BURNS", stage: "RIS", start: "20:50", end: "21:20" },
      { name: "THE COATHANGER SOLUTION", stage: "RIS", start: "20:00", end: "20:30" },
      { name: "A MURDER OF CROWS", stage: "RIS", start: "19:10", end: "19:40" },
      { name: "DEFUSED", stage: "RIS", start: "18:20", end: "18:50" },
      { name: "VERSAINTS", stage: "RIS", start: "17:30", end: "18:00" },
      { name: "CRITICAL CANDY", stage: "RIS", start: "16:40", end: "17:10" },
      { name: "CATFIGHT", stage: "RIS", start: "15:50", end: "16:20" },
      { name: "WRISHLAS", stage: "RIS", start: "15:00", end: "15:30" },
      { name: "R.P.C.", stage: "RIS", start: "14:10", end: "14:40" },
      { name: "THRONK!", stage: "RIS", start: "13:20", end: "13:50" },
      { name: "MALAD", stage: "RIS", start: "12:30", end: "13:00" },
      // Almost Acoustic
      { name: "JOHNNY MOPED (ACOUSTIC)", stage: "Almost Acoustic", start: "21:00", end: "21:45" },
      { name: "I, DORIS (ACOUSTIC)", stage: "Almost Acoustic", start: "20:15", end: "20:50" },
      { name: "THE OUTCASTS (ACOUSTIC)", stage: "Almost Acoustic", start: "19:30", end: "20:05" },
      { name: "LAST TREE SQUAD (ACOUSTIC)", stage: "Almost Acoustic", start: "18:40", end: "19:15" },
      { name: "CHRON GEN (ACOUSTIC)", stage: "Almost Acoustic", start: "17:50", end: "18:25" },
      { name: "RANDOM HAND (ACOUSTIC)", stage: "Almost Acoustic", start: "17:00", end: "17:35" },
      { name: "MENACE WITH LEIGH HEGGARTY PLAY G.L.C. RIP", stage: "Almost Acoustic", start: "16:10", end: "16:45" },
      { name: "JO CARLEY AND THE OLD DRY SKULLS", stage: "Almost Acoustic", start: "15:25", end: "16:00" },
      { name: "VOODOO RADIO (ACOUSTIC)", stage: "Almost Acoustic", start: "14:40", end: "15:10" },
      { name: "EMILY FLEA PLAYS THE DAMNED", stage: "Almost Acoustic", start: "13:55", end: "14:30" },
      { name: "CRYSSIS", stage: "Almost Acoustic", start: "13:15", end: "13:45" },
      { name: "FIRE EXIT (ACOUSTIC)", stage: "Almost Acoustic", start: "12:35", end: "13:05" },
      // The Old Vic
      { name: "DJ SCRATCHY", stage: "The Old Vic", start: "18:50", end: "20:30" },
      { name: "STATIC KILL ACOUSTIC SESSIONS (FRI)", stage: "The Old Vic", start: "16:45", end: "18:45" },
      { name: "CHRISTMAS KWON FROM 18 FEVERS", stage: "The Old Vic", start: "15:55", end: "16:30" },
      { name: "CAROL HODGE", stage: "The Old Vic", start: "15:15", end: "15:45" },
      { name: "MAURI CLASH", stage: "The Old Vic", start: "14:35", end: "15:05" },
      { name: "BITZY", stage: "The Old Vic", start: "13:55", end: "14:25" },
      { name: "RAT BOY'S MAGIC SHOW (FRI)", stage: "The Old Vic", start: "13:25", end: "13:45" },
      { name: "BINGO WITH MAX SPLODGE (FRI)", stage: "The Old Vic", start: "12:45", end: "13:15" }
    ]
  },

  Saturday: {
    date: "Sat 8 Aug 2026",
    bands: [
      // Empress Ballroom
      { name: "COCK SPARRER", stage: "Empress Ballroom", start: "23:25", end: "00:35" },
      { name: "COCKNEY REJECTS", stage: "Empress Ballroom", start: "21:55", end: "22:55" },
      { name: "DIE TOTEN HOSEN", stage: "Empress Ballroom", start: "20:25", end: "21:25" },
      { name: "GBH", stage: "Empress Ballroom", start: "19:10", end: "20:00" },
      { name: "CHRON GEN", stage: "Empress Ballroom", start: "17:55", end: "18:50" },
      { name: "SUBHUMANS", stage: "Empress Ballroom", start: "16:45", end: "17:35" },
      { name: "GIMP FIST", stage: "Empress Ballroom", start: "15:40", end: "16:25" },
      { name: "999", stage: "Empress Ballroom", start: "14:35", end: "15:20" },
      { name: "LOS FASTIDIOS", stage: "Empress Ballroom", start: "13:35", end: "14:15" },
      { name: "PUBIC ENEMY", stage: "Empress Ballroom", start: "12:40", end: "13:15" },
      // Club Casbah
      { name: "SKIDS", stage: "Club Casbah", start: "23:20", end: "00:20" },
      { name: "THE CHAMELEONS", stage: "Club Casbah", start: "21:50", end: "22:50" },
      { name: "THE WURZELS", stage: "Club Casbah", start: "20:20", end: "21:20" },
      { name: "SPUNK VOLCANO & THE ERUPTIONS", stage: "Club Casbah", start: "19:10", end: "19:55" },
      { name: "DEADLINE", stage: "Club Casbah", start: "18:10", end: "18:50" },
      { name: "TEAR UP", stage: "Club Casbah", start: "17:10", end: "17:50" },
      { name: "KNOCK OFF", stage: "Club Casbah", start: "16:10", end: "16:50" },
      { name: "PARANOID VISIONS", stage: "Club Casbah", start: "15:10", end: "15:50" },
      { name: "HUNG LIKE HANRATTY", stage: "Club Casbah", start: "14:15", end: "14:50" },
      { name: "SPUNK", stage: "Club Casbah", start: "13:25", end: "13:55" },
      { name: "PHAT PROBLEM", stage: "Club Casbah", start: "12:35", end: "13:05" },
      // Opera House
      { name: "PENETRATION", stage: "Opera House", start: "23:15", end: "00:15" },
      { name: "DAVE FORMULA & NOKO", stage: "Opera House", start: "22:00", end: "22:50" },
      { name: "SPIZZ ENERGI", stage: "Opera House", start: "20:45", end: "21:30" },
      { name: "SALFORD JETS", stage: "Opera House", start: "19:40", end: "20:25" },
      { name: "RUTS D.C. ACOUSTIC", stage: "Opera House", start: "18:35", end: "19:20" },
      { name: "ANDERSON FROM CRAZYHEAD", stage: "Opera House", start: "17:30", end: "18:15" },
      { name: "THE OUTCASTS", stage: "Opera House", start: "16:30", end: "17:10" },
      { name: "JOHNNY MOPED", stage: "Opera House", start: "15:30", end: "16:10" },
      { name: "HEATHEN APOSTLES", stage: "Opera House", start: "14:30", end: "15:10" },
      { name: "I, DORIS", stage: "Opera House", start: "13:30", end: "14:10" },
      { name: "VOODOO RADIO", stage: "Opera House", start: "12:40", end: "13:10" },
      // Conference Circle
      { name: "EXTC", stage: "Conference Circle", start: "23:15", end: "00:15" },
      { name: "RICKY WARWICK & THE FIGHTING HEARTS", stage: "Conference Circle", start: "21:35", end: "22:20" },
      // Arena
      { name: "RUBELLA BALLET", stage: "Arena", start: "23:35", end: "00:25" },
      { name: "NOTSENSIBLES", stage: "Arena", start: "22:30", end: "23:15" },
      { name: "THE ATTACK", stage: "Arena", start: "21:30", end: "22:10" },
      { name: "LAST TREE SQUAD", stage: "Arena", start: "20:25", end: "21:05" },
      { name: "LIBERTY & JUSTICE", stage: "Arena", start: "19:15", end: "19:55" },
      { name: "GRIPPERS", stage: "Arena", start: "18:15", end: "18:55" },
      { name: "THE GAKK", stage: "Arena", start: "17:15", end: "17:55" },
      { name: "FIRE EXIT", stage: "Arena", start: "16:15", end: "16:55" },
      { name: "DEAD POLLYS", stage: "Arena", start: "15:20", end: "15:55" },
      { name: "4FT FINGERS", stage: "Arena", start: "14:25", end: "15:00" },
      { name: "DIAZ BROTHERS", stage: "Arena", start: "13:35", end: "14:05" },
      { name: "UNDER THE INFLUENCE", stage: "Arena", start: "12:45", end: "13:15" },
      // After Dark in Pavilion
      { name: "DISORDER", stage: "After Dark", start: "00:35", end: "01:15" },
      { name: "THE RESTARTS", stage: "After Dark", start: "23:35", end: "00:15" },
      { name: "RESISTANCE 77", stage: "After Dark", start: "22:35", end: "23:15" },
      { name: "PUSSYLIQUOR", stage: "After Dark", start: "21:40", end: "22:15" },
      // RIS in Pavilion
      { name: "XTINE AND THE RECKLESS HEARTS", stage: "RIS", start: "20:50", end: "21:20" },
      { name: "RIVER RATTS", stage: "RIS", start: "20:00", end: "20:30" },
      { name: "NOTHING THRIVES", stage: "RIS", start: "19:10", end: "19:40" },
      { name: "THE JUNGLES", stage: "RIS", start: "18:20", end: "18:50" },
      { name: "THE NANAZ", stage: "RIS", start: "17:30", end: "18:00" },
      { 
